-- CTP Core — Postgres delta 0014: catch the cloud DB up to SQLite 0013.
ALTER TABLE part ADD COLUMN IF NOT EXISTS diagram_ref TEXT;

CREATE TABLE IF NOT EXISTS part_alias (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phrase_norm  TEXT    NOT NULL,
  part_id      BIGINT  NOT NULL REFERENCES part(id) ON DELETE CASCADE,
  polarity     INTEGER NOT NULL DEFAULT 1 CHECK (polarity IN (1, -1)),
  hits         INTEGER NOT NULL DEFAULT 1,
  source       TEXT    NOT NULL DEFAULT 'operator'
                 CHECK (source IN ('operator','seed','import')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  rev          INTEGER NOT NULL DEFAULT 1,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at   TIMESTAMPTZ,
  origin       TEXT,
  UNIQUE (phrase_norm, part_id, polarity)
);
CREATE INDEX IF NOT EXISTS part_alias_phrase_idx ON part_alias(phrase_norm, polarity);
CREATE INDEX IF NOT EXISTS part_alias_part_idx   ON part_alias(part_id);

CREATE TABLE IF NOT EXISTS price_tier (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code           TEXT NOT NULL UNIQUE,
  name           TEXT NOT NULL,
  discount_bps   INTEGER NOT NULL DEFAULT 0    CHECK (discount_bps   BETWEEN 0 AND 9000),
  min_margin_bps INTEGER NOT NULL DEFAULT 1500 CHECK (min_margin_bps BETWEEN 0 AND 9000),
  rev            INTEGER NOT NULL DEFAULT 1,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at     TIMESTAMPTZ,
  origin         TEXT
);

CREATE TABLE IF NOT EXISTS part_cost (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id      BIGINT  NOT NULL REFERENCES part(id) ON DELETE CASCADE,
  currency     TEXT    NOT NULL DEFAULT 'ZAR',
  amount_minor INTEGER NOT NULL CHECK (amount_minor >= 0),
  valid_from   TIMESTAMPTZ NOT NULL DEFAULT now(),
  source       TEXT,
  rev          INTEGER NOT NULL DEFAULT 1,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at   TIMESTAMPTZ,
  origin       TEXT,
  UNIQUE (part_id, currency, valid_from)
);
CREATE INDEX IF NOT EXISTS part_cost_part_idx ON part_cost(part_id, currency, valid_from DESC);

DROP VIEW IF EXISTS part_detail;

ALTER TABLE price                 DROP CONSTRAINT IF EXISTS price_pkey;
ALTER TABLE price                 ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE price                 ADD CONSTRAINT price_natural_key UNIQUE (part_id, tier, currency, valid_from);

ALTER TABLE stock_policy          DROP CONSTRAINT IF EXISTS stock_policy_pkey;
ALTER TABLE stock_policy          ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE stock_policy          ADD CONSTRAINT stock_policy_natural_key UNIQUE (part_id, location_id);

ALTER TABLE part_fitment          DROP CONSTRAINT IF EXISTS part_fitment_pkey;
ALTER TABLE part_fitment          ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE part_fitment          ADD CONSTRAINT part_fitment_natural_key UNIQUE (part_id, vehicle_id, engine);

ALTER TABLE part_diagram_callout  DROP CONSTRAINT IF EXISTS part_diagram_callout_pkey;
ALTER TABLE part_diagram_callout  ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE part_diagram_callout  ADD CONSTRAINT part_diagram_callout_natural_key UNIQUE (part_id, diagram_id);

CREATE VIEW part_detail AS
SELECT
  p.id, p.sku, p.locator, p.name, p.description, p.side,
  p.make, p.model, p.drawing_no, p.diagram_item_no,
  p.catalogue_pn, p.inventory_pn, p.mpn,
  c.code AS category_code, c.name AS category_name,
  p.status, p.match_status, p.notes, p.list_price_minor,
  COALESCE((SELECT SUM(delta) FROM stock_movement WHERE part_id = p.id), 0) AS qty_on_hand,
  (SELECT bin FROM stock_policy WHERE part_id = p.id LIMIT 1) AS bin,
  NULL::INTEGER AS price_usd_minor,
  (SELECT amount_minor FROM part_cost
     WHERE part_id = p.id AND currency = 'ZAR' AND deleted_at IS NULL
     ORDER BY valid_from DESC LIMIT 1) AS price_zar_minor,
  (SELECT path FROM part_image
     WHERE part_id = p.id AND deleted_at IS NULL
     ORDER BY is_primary DESC, sort_order LIMIT 1) AS primary_image,
  (SELECT glb_path FROM part_model
     WHERE part_id = p.id AND deleted_at IS NULL LIMIT 1) AS model_3d,
  (SELECT d.image_path FROM diagram d
     WHERE d.drawing_key = 'SEC' || p.category_id LIMIT 1) AS diagram_image,
  p.diagram_ref AS diagram_item
FROM part p
JOIN category c ON c.id = p.category_id
WHERE p.deleted_at IS NULL;

ALTER TABLE part_alias ENABLE ROW LEVEL SECURITY;
ALTER TABLE part_cost  ENABLE ROW LEVEL SECURITY;
ALTER TABLE price_tier ENABLE ROW LEVEL SECURITY;
