-- ============================================================================
--  CTP Core — PURCHASING, GOODS RECEIPT, LANDED COST AND REBATES (server 0039)
--
--  Desktop counterpart: app/src-tauri/migrations/0024_purchasing.sql, which is
--  the same schema in SQLite and ships in the desktop build. This file is the
--  cloud half. Apply in the Supabase SQL editor.
--
--  WHAT THIS IS FOR: the system could only watch stock LEAVE. This is the half
--  that records it ARRIVING, and therefore the half that can say what a part
--  truly cost.
--
--      true cost = invoice + freight + duty + clearing − rebate earned
--
--  Landed costing and rebates are the two halves of one number. Building either
--  alone produces a figure that is confidently wrong, which is why they land
--  together.
--
--  ────────────────────────────────────────────────────────────────────────
--  THE ONE RULE THAT MUST NOT BE BROKEN — TWO COST FIGURES, NEVER ONE
--
--    unit_cost_invoiced_minor  invoice + freight + duty + clearing. Money
--                              actually spent. CERTAIN. The ONLY figure a price
--                              floor, a stock valuation or an accounting export
--                              may read.
--    unit_cost_expected_minor  invoiced − rebate attributable. Contingent.
--                              Reporting and buying decisions only.
--
--  They are separate columns from the first commit because merging them later
--  is easy and unpicking them is not. If an unearned rebate reduces the figure
--  the price floor reads, the app funds discounts with money that may never
--  arrive — and an importer can discount its way to missing the very threshold
--  that was paying for the discount.
--  ────────────────────────────────────────────────────────────────────────
--
--  WHY part_landed_cost IS A NEW TABLE rather than columns on part_cost:
--  part_cost is keyed (part_id, currency, valid_from) and holds 159 rows
--  transcribed from a supplier PRICE LIST. Two receipts of the same part at the
--  same instant collide on that key, and widening it means rebuilding a table
--  the quoting path reads. The additive answer keys on (part_id, receipt_id) —
--  which is what a landed cost actually is, one per part per arrival — and
--  leaves the price-list rows as an honest fallback.
--
--  NO STOCK IS WRITTEN BY THIS FILE, and none by the module either: receiving
--  posts to the existing stock_movement ledger and nowhere else. There is no
--  second stock concept and no quantity column anywhere below.
--
--  MONEY is integer minor units. FX RATES are integer parts-per-million
--  (18.4732 ZAR/USD = 18473200). Integers because a float rate multiplied
--  across 161 lines produces a total that does not reconcile with the invoice.
--
--  SECURITY: every table here is cost data — landed cost, margins, supplier
--  terms, rebate rates. All of it is staff-only, matching the decision already
--  made for price (0025), part_cost and price_tier. PowerSync replicates as
--  powersync_role (BYPASSRLS) so device sync is unaffected; these tables are
--  deliberately NOT added to any client sync stream by this migration.
--
--  Idempotent: safe to re-run.
-- ============================================================================

begin;

-- ── 1. supplier ────────────────────────────────────────────────────────────
create table if not exists public.supplier (
  id            bigint generated by default as identity primary key,
  code          text not null unique,
  name          text not null,
  contact text, phone text, email text, address text,
  currency      text not null default 'ZAR',
  -- Not decoration: under EXW the buyer pays everything and freight is a
  -- landed-cost component; under CIF the supplier's invoice already contains
  -- it and adding it again double-counts.
  incoterm      text check (incoterm is null or incoterm in
                  ('EXW','FCA','FOB','CFR','CIF','CPT','CIP','DAP','DPU','DDP')),
  payment_terms text,
  lead_time_days integer check (lead_time_days is null or lead_time_days >= 0),
  notes         text,
  client_uuid   text,
  rev           integer not null default 1,
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz, origin text
);
create unique index if not exists supplier_uuid_idx
  on public.supplier(client_uuid) where client_uuid is not null;

-- ── 2. purchase order ──────────────────────────────────────────────────────
create table if not exists public.purchase_order (
  id            bigint generated by default as identity primary key,
  number        text not null unique,
  supplier_id   bigint not null references public.supplier(id),
  status        text not null default 'draft' check (status in
                  ('draft','sent','acknowledged','part_received','received',
                   'closed','cancelled')),
  currency      text not null default 'ZAR',
  -- The rate ASSUMED when ordering; the receipt carries what actually applied.
  -- The difference is a real cost movement, not an error to hide.
  fx_rate_ppm_expected bigint check (fx_rate_ppm_expected is null
                                     or fx_rate_ppm_expected > 0),
  ordered_at timestamptz, expected_at timestamptz,
  notes text, client_uuid text,
  actor_id uuid, actor_label text, actor_source text,
  rev integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz, origin text
);
create index if not exists po_supplier_idx
  on public.purchase_order(supplier_id, status);
create unique index if not exists po_uuid_idx
  on public.purchase_order(client_uuid) where client_uuid is not null;

create table if not exists public.purchase_order_line (
  id            bigint generated by default as identity primary key,
  order_id      bigint not null references public.purchase_order(id) on delete cascade,
  part_id       bigint not null references public.part(id),
  qty_ordered   integer not null check (qty_ordered > 0),
  unit_cost_minor bigint not null default 0 check (unit_cost_minor >= 0),
  expected_at   timestamptz,
  rev integer not null default 1,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz, origin text,
  unique (order_id, part_id)
);
create index if not exists pol_order_idx on public.purchase_order_line(order_id);

-- NOTE, deliberately absent: no qty_received column. Received quantity is
-- SUM(goods_receipt_line.qty_received) over posted receipts. A stored counter
-- is a second source of truth and drifts the first time a receipt is reversed.

-- ── 3. goods receipt ───────────────────────────────────────────────────────
create table if not exists public.goods_receipt (
  id            bigint generated by default as identity primary key,
  number        text not null unique,
  supplier_id   bigint references public.supplier(id),      -- null: opening balance
  order_id      bigint references public.purchase_order(id),-- null: no PO existed
  kind          text not null default 'purchase' check (kind in
                  ('purchase','opening','warranty_replacement','return_in')),
  location_id   bigint not null references public.location(id),
  received_at   timestamptz not null default now(),
  supplier_invoice_ref text,
  supplier_invoice_total_minor bigint check (supplier_invoice_total_minor is null
                                             or supplier_invoice_total_minor >= 0),
  invoice_currency text not null default 'ZAR',
  fx_rate_ppm   bigint not null default 1000000 check (fx_rate_ppm > 0),
  -- 1 when the costs here are a stated estimate rather than a measurement: the
  -- opening balance, or a receipt costed before the clearing agent invoiced.
  -- It exists so those numbers can never be quoted as fact.
  cost_is_estimated boolean not null default false,
  -- 'draft' accumulates lines and writes NO stock. Receiving a container takes
  -- hours, gets interrupted, and the person counting is not the person holding
  -- the invoice. POSTING is the single moment stock moves. Without a draft
  -- state a half-counted container is already in stock and the shortfall looks
  -- like theft.
  status        text not null default 'draft'
                check (status in ('draft','posted','reversed')),
  posted_at timestamptz, reversed_at timestamptz,
  notes text, client_uuid text,
  actor_id uuid, actor_label text, actor_source text,
  rev integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz, origin text
);
create index if not exists gr_order_idx on public.goods_receipt(order_id);
create index if not exists gr_supplier_idx
  on public.goods_receipt(supplier_id, received_at);
create unique index if not exists gr_uuid_idx
  on public.goods_receipt(client_uuid) where client_uuid is not null;

create table if not exists public.goods_receipt_line (
  id            bigint generated by default as identity primary key,
  receipt_id    bigint not null references public.goods_receipt(id) on delete cascade,
  part_id       bigint not null references public.part(id),
  -- Nullable on purpose. Suppliers send things you did not order; forcing a
  -- match means the receiver either lies or stops, and both are worse than
  -- recording what actually arrived and flagging it.
  order_line_id bigint references public.purchase_order_line(id),
  qty_received  integer not null check (qty_received > 0),
  unit_cost_minor bigint not null default 0 check (unit_cost_minor >= 0),
  rev integer not null default 1,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz, origin text,
  unique (receipt_id, part_id)
);
create index if not exists grl_receipt_idx on public.goods_receipt_line(receipt_id);
create index if not exists grl_part_idx on public.goods_receipt_line(part_id);

-- ── 4. landed cost components ──────────────────────────────────────────────
-- Costs arrive AFTER the goods — the clearing agent invoices in arrears — so a
-- receipt must accept components after posting and after the stock is selling.
-- Landed cost is recomputed as components arrive, not calculated once.
create table if not exists public.receipt_cost (
  id            bigint generated by default as identity primary key,
  receipt_id    bigint not null references public.goods_receipt(id) on delete cascade,
  component     text not null check (component in
                  ('freight_sea','freight_air','freight_road','duty','vat_import',
                   'clearing','insurance','handling','finance','other')),
  amount_minor  bigint not null check (amount_minor >= 0),
  currency      text not null default 'ZAR',
  fx_rate_ppm   bigint not null default 1000000 check (fx_rate_ppm > 0),
  -- Each component allocates on its own basis: freight is properly weight,
  -- duty is a percentage of customs value, clearing is per consignment.
  allocation    text not null default 'by_value' check (allocation in
                  ('by_value','by_weight','by_units','direct')),
  direct_part_id bigint references public.part(id),
  -- ⚠ IMPORT VAT IS USUALLY RECLAIMABLE AND THEREFORE NOT A LANDED COST. It is
  --   in the list because it appears on the clearing agent's invoice and
  --   somebody will type it in. This flag decides whether it lands on the part.
  is_landed     boolean not null default true,
  supplier_ref  text, notes text,
  rev integer not null default 1,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz, origin text,
  check (allocation <> 'direct' or direct_part_id is not null)
);
create index if not exists rc_receipt_idx on public.receipt_cost(receipt_id);

-- ── 5. the landed cost itself — two figures, never one ─────────────────────
create table if not exists public.part_landed_cost (
  id            bigint generated by default as identity primary key,
  part_id       bigint not null references public.part(id) on delete cascade,
  receipt_id    bigint references public.goods_receipt(id) on delete cascade,
  currency      text not null default 'ZAR',
  qty           integer not null check (qty > 0),

  unit_invoice_minor  bigint not null default 0 check (unit_invoice_minor  >= 0),
  unit_freight_minor  bigint not null default 0 check (unit_freight_minor  >= 0),
  unit_duty_minor     bigint not null default 0 check (unit_duty_minor     >= 0),
  unit_clearing_minor bigint not null default 0 check (unit_clearing_minor >= 0),
  unit_other_minor    bigint not null default 0 check (unit_other_minor    >= 0),

  -- THE CERTAIN FIGURE. The only one a price floor may read.
  unit_cost_invoiced_minor bigint not null check (unit_cost_invoiced_minor >= 0),
  -- THE CONTINGENT FIGURE. Reporting and buying decisions only.
  unit_rebate_minor        bigint not null default 0 check (unit_rebate_minor >= 0),
  unit_cost_expected_minor bigint not null check (unit_cost_expected_minor >= 0),
  -- Which accrual states were allowed to contribute. 'settled' is the default
  -- and the safe one; 'accrued' includes money not yet in hand and must never
  -- reach a price floor.
  rebate_basis  text not null default 'settled'
                check (rebate_basis in ('settled','claimed','accrued','none')),

  is_estimated  boolean not null default false,
  valid_from    timestamptz not null default now(),
  source        text,
  rev integer not null default 1,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz, origin text,
  -- a rebate reduces cost, never adds to it
  check (unit_cost_expected_minor <= unit_cost_invoiced_minor)
);
create unique index if not exists plc_part_receipt_idx
  on public.part_landed_cost(part_id, receipt_id) where receipt_id is not null;
create index if not exists plc_part_idx
  on public.part_landed_cost(part_id, valid_from desc);

-- part_cost keeps its 159 price-list rows and becomes the FALLBACK. The column
-- says what a row is without anyone having to parse the free-text source.
alter table public.part_cost add column if not exists basis text;
update public.part_cost set basis = 'price_list' where basis is null;

-- ── 6. discrepancies — a short is a CLAIM, not a stock adjustment ──────────
-- The instinct is to treat a short as an adjustment: expected 100, got 97,
-- write down 3. That is wrong in the direction that loses money. An adjustment
-- says "we were mistaken about what we had". A short says "we paid for 100,
-- received 97, and the supplier owes us 3". One is a correction; the other is
-- an asset.
create table if not exists public.supplier_claim (
  id            bigint generated by default as identity primary key,
  number        text not null unique,
  supplier_id   bigint not null references public.supplier(id),
  kind          text not null check (kind in
                  ('short','damage','warranty','core_return','price_variance','rebate')),
  origin_type   text check (origin_type is null or origin_type in
                  ('receipt_discrepancy','rebate_accrual','manual')),
  origin_id     bigint,
  value_minor   bigint not null check (value_minor >= 0),
  currency      text not null default 'ZAR',
  -- The gap between 'open' and 'submitted' is where recovery money actually
  -- dies. Not in the calculation — in the follow-up.
  state         text not null default 'open' check (state in
                  ('open','submitted','acknowledged','disputed','settled','written_off')),
  submitted_at timestamptz, settled_at timestamptz,
  settlement_type text check (settlement_type is null or settlement_type in
                  ('credit_note','deduction','cash')),
  settlement_ref text,
  settled_value_minor bigint check (settled_value_minor is null
                                    or settled_value_minor >= 0),
  notes text, client_uuid text,
  actor_id uuid, actor_label text, actor_source text,
  rev integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz, origin text
);
create index if not exists sc_supplier_idx
  on public.supplier_claim(supplier_id, state);
create unique index if not exists sc_uuid_idx
  on public.supplier_claim(client_uuid) where client_uuid is not null;

create table if not exists public.receipt_discrepancy (
  id            bigint generated by default as identity primary key,
  receipt_id    bigint not null references public.goods_receipt(id) on delete cascade,
  receipt_line_id bigint references public.goods_receipt_line(id),
  part_id       bigint not null references public.part(id),
  kind          text not null check (kind in
                  ('short','over','damaged','wrong_part','quality')),
  qty           integer not null check (qty > 0),
  -- 'damaged' describes the goods, not the decision. The disposition is what
  -- says whether stock increased:
  --   reject            no stock, claim raised   (a short is always this)
  --   accept_and_claim  stock increases, claim raised
  --   scrap_and_claim   stock increases then written off, claim raised
  --   accept_no_claim   stock increases, no claim
  disposition   text not null default 'reject' check (disposition in
                  ('reject','accept_and_claim','scrap_and_claim','accept_no_claim')),
  claim_value_minor bigint not null default 0 check (claim_value_minor >= 0),
  currency      text not null default 'ZAR',
  claim_id      bigint references public.supplier_claim(id),
  photo_ref     text,   -- evidence at the crate beats a claim three weeks later
  notes text,
  actor_id uuid, actor_label text, actor_source text,
  rev integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz, origin text
);
create index if not exists rd_receipt_idx on public.receipt_discrepancy(receipt_id);

-- ── 7. rebate agreements — the rule is DATA, not code ──────────────────────
-- Rebate agreements are renegotiated annually. A system that needs a developer
-- for each new agreement is wrong even if the terms were known perfectly, and
-- here they are not known at all yet. So every part of the rule is a field and
-- the supplier's answer becomes data entry rather than a release.
create table if not exists public.rebate_agreement (
  id            bigint generated by default as identity primary key,
  code          text not null unique,
  supplier_id   bigint not null references public.supplier(id),
  name          text,
  -- BASIS changes behaviour most. 'purchases' is knowable the moment a
  -- container is booked in; 'sales' cannot be, so it accrues as stock moves
  -- and reconciles when the period closes.
  basis         text not null default 'purchases'
                check (basis in ('purchases','sales')),
  measure       text not null default 'volume_value'
                check (measure in ('volume_value','volume_qty','growth','flat_percent')),
  scope         text not null default 'supplier'
                check (scope in ('supplier','product_group','part')),
  period_start  date not null,
  period_end    date not null,
  -- ⚠ THE FIELD THAT IS EASY TO MISS AND EXPENSIVE TO MISS.
  --   incremental   2% on the first R1m, 3% on the next. Crossing affects only
  --                 what comes after.
  --   retrospective cross R2m and 3% applies to the WHOLE period from the first
  --                 rand. Crossing retroactively revalues everything accrued.
  --   Being R50 000 short of a threshold does not cost 3% of R50 000 under
  --   retrospective — it costs 1% of R2m.
  tier_mode     text not null default 'incremental'
                check (tier_mode in ('incremental','retrospective')),
  baseline_period_start date, baseline_period_end date,
  settlement    text not null default 'credit_note'
                check (settlement in ('credit_note','deduction','cash')),
  currency      text not null default 'ZAR',
  status        text not null default 'draft'
                check (status in ('draft','active','closed','superseded')),
  -- An agreement that changes is SUPERSEDED, never edited. Last year's claim
  -- must still reproduce last year's number when an auditor asks.
  superseded_by_id bigint references public.rebate_agreement(id),
  -- true when the terms are a working assumption rather than the supplier's
  -- actual agreement. Every screen showing a derived figure must say so.
  is_provisional boolean not null default true,
  notes text, client_uuid text,
  rev integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz, origin text,
  check (period_end > period_start),
  check (measure <> 'growth' or (baseline_period_start is not null
                                 and baseline_period_end is not null))
);
create index if not exists ra_supplier_idx
  on public.rebate_agreement(supplier_id, status, period_start);

create table if not exists public.rebate_agreement_scope (
  id            bigint generated by default as identity primary key,
  agreement_id  bigint not null references public.rebate_agreement(id) on delete cascade,
  category_id   bigint references public.category(id),
  part_id       bigint references public.part(id),
  rev integer not null default 1,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz, origin text,
  check ((category_id is not null) <> (part_id is not null))
);
create unique index if not exists ras_cat_idx
  on public.rebate_agreement_scope(agreement_id, category_id) where category_id is not null;
create unique index if not exists ras_part_idx
  on public.rebate_agreement_scope(agreement_id, part_id) where part_id is not null;

-- A stepped scheme is data, not logic. threshold_to null = open-ended top tier.
create table if not exists public.rebate_tier (
  id            bigint generated by default as identity primary key,
  agreement_id  bigint not null references public.rebate_agreement(id) on delete cascade,
  threshold_from bigint not null check (threshold_from >= 0),
  threshold_to   bigint check (threshold_to is null or threshold_to > threshold_from),
  rate_bps      integer not null check (rate_bps between 0 and 10000),
  rev integer not null default 1,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz, origin text,
  unique (agreement_id, threshold_from)
);
create index if not exists rt_agreement_idx
  on public.rebate_tier(agreement_id, threshold_from);

-- ── 8. the accrual ledger — append-only, exactly like stock_movement ───────
-- A rebate accrual is a financial assertion. It is corrected by a REVERSING
-- entry that points at what it reverses, never by an UPDATE. When the supplier
-- disputes a claim eight months later the argument is won by showing the
-- derivation, and a mutable table has none to show.
--
-- The trap this avoids: a sales-based rebate accrued on a sale later credited
-- must reverse. If accruals are only ever added, a business with a normal
-- return rate overstates what it is owed every period.
create table if not exists public.rebate_accrual (
  id            bigint generated by default as identity primary key,
  agreement_id  bigint not null references public.rebate_agreement(id),
  period_start  date not null,
  period_end    date not null,
  source_type   text not null check (source_type in
                  ('goods_receipt','sales_order','manual_adjustment','tier_uplift')),
  source_id     bigint,
  part_id       bigint references public.part(id),
  qty           integer not null default 0,
  measured_value_minor bigint not null default 0,
  rate_bps_applied integer not null default 0,
  -- Signed: a reversal or downward restatement is negative. The sum over a
  -- period is what is earned, which is why nothing here is ever deleted.
  amount_minor  bigint not null,
  currency      text not null default 'ZAR',
  state         text not null default 'accrued' check (state in
                  ('accrued','claimable','claimed','settled','reversed')),
  reverses_id   bigint references public.rebate_accrual(id),
  claim_id      bigint references public.supplier_claim(id),
  note          text,
  client_uuid   text not null unique,   -- same idempotency contract as the ledger
  actor_id uuid, actor_label text, actor_source text,
  created_at    timestamptz not null default now(),
  origin        text
);
create index if not exists acc_agreement_idx
  on public.rebate_accrual(agreement_id, period_start, state);
create index if not exists acc_source_idx
  on public.rebate_accrual(source_type, source_id);
create index if not exists acc_part_idx on public.rebate_accrual(part_id);

-- ── 9. views ───────────────────────────────────────────────────────────────
create or replace view public.po_line_status as
  select pol.id as order_line_id, pol.order_id, pol.part_id, pol.qty_ordered,
         coalesce((select sum(grl.qty_received)
                     from public.goods_receipt_line grl
                     join public.goods_receipt gr on gr.id = grl.receipt_id
                    where grl.order_line_id = pol.id
                      and gr.status = 'posted'
                      and grl.deleted_at is null), 0) as qty_received
    from public.purchase_order_line pol
   where pol.deleted_at is null;

-- The newest landed cost if there is one, else the price-list fallback. BOTH
-- figures are carried through; anything that constrains a price reads
-- cost_invoiced_minor and nothing else.
create or replace view public.part_current_cost as
  select p.id as part_id,
         coalesce(l.unit_cost_invoiced_minor, pc.amount_minor) as cost_invoiced_minor,
         coalesce(l.unit_cost_expected_minor, pc.amount_minor) as cost_expected_minor,
         coalesce(l.unit_rebate_minor, 0)                      as rebate_minor,
         coalesce(l.currency, pc.currency, 'ZAR')              as currency,
         case when l.id is not null then 'landed'
              when pc.part_id is not null then 'price_list'
              else 'none' end                                  as basis,
         coalesce(l.is_estimated, true)                        as is_estimated
    from public.part p
    left join lateral (
      select * from public.part_landed_cost x
       where x.part_id = p.id and x.deleted_at is null
       order by x.valid_from desc, x.id desc limit 1) l on true
    left join lateral (
      select * from public.part_cost y
       where y.part_id = p.id
       order by y.valid_from desc limit 1) pc on true
   where p.deleted_at is null;

-- Rebate exposure: how much of reported profit depends on claims being made
-- and honoured. Nothing computed this before.
create or replace view public.rebate_position as
  select a.id as agreement_id, a.code, a.supplier_id, a.basis, a.measure,
         a.tier_mode, a.period_start, a.period_end, a.is_provisional,
         coalesce(sum(r.amount_minor), 0) as earned_minor,
         coalesce(sum(r.amount_minor) filter (where r.state='accrued'), 0)   as accrued_minor,
         coalesce(sum(r.amount_minor) filter (where r.state='claimable'), 0) as claimable_minor,
         coalesce(sum(r.amount_minor) filter (where r.state='claimed'), 0)   as claimed_minor,
         coalesce(sum(r.amount_minor) filter (where r.state='settled'), 0)   as settled_minor,
         coalesce(sum(r.amount_minor) filter
                  (where r.state in ('accrued','claimable','claimed')), 0)   as exposure_minor
    from public.rebate_agreement a
    left join public.rebate_accrual r
      on r.agreement_id = a.id and r.state <> 'reversed'
   where a.deleted_at is null
   group by a.id;

-- ── 10. rev triggers ───────────────────────────────────────────────────────
-- touch_rev() from 0034 already exists. Installing it declaratively on every
-- rev-bearing table means new tables are covered without anyone maintaining a
-- list — which is the failure mode 0034 was written to avoid.
do $$
declare t text;
begin
  for t in
    select c.table_name
      from information_schema.columns c
      join information_schema.columns u
        on u.table_schema = c.table_schema and u.table_name = c.table_name
       and u.column_name = 'updated_at'
      join information_schema.tables tb
        on tb.table_schema = c.table_schema and tb.table_name = c.table_name
       and tb.table_type = 'BASE TABLE'
     where c.table_schema = 'public' and c.column_name = 'rev'
     order by c.table_name
  loop
    execute format('drop trigger if exists %I on public.%I', t || '_touch_rev', t);
    execute format(
      'create trigger %I before update on public.%I '
      'for each row execute function public.touch_rev()', t || '_touch_rev', t);
  end loop;
end $$;

-- rebate_accrual deliberately gets NO trigger, for the same reason
-- stock_movement has none: it is append-only, so a version counter would be
-- meaningless. It has no rev column, so the loop above skips it on its own.

-- ── 11. RLS and grants — all of this is cost data, so staff only ───────────
-- Matches the decision already made for price (0025), part_cost and price_tier.
-- A customer account must never read landed cost, supplier terms or rebate
-- rates off the Data API.
do $$
declare t text;
begin
  foreach t in array array['supplier','purchase_order','purchase_order_line',
                           'goods_receipt','goods_receipt_line','receipt_cost',
                           'part_landed_cost','receipt_discrepancy','supplier_claim',
                           'rebate_agreement','rebate_agreement_scope','rebate_tier',
                           'rebate_accrual']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t || '_staff_read', t);
    execute format('create policy %I on public.%I for select to authenticated using (is_staff())',
                   t || '_staff_read', t);
    execute format('drop policy if exists %I on public.%I', t || '_staff_write', t);
    execute format('create policy %I on public.%I for all to authenticated using (is_staff()) with check (is_staff())',
                   t || '_staff_write', t);
    -- Postgres checks table GRANTs BEFORE RLS, so a policy without a grant is
    -- unreachable code. 0015 learned this the hard way.
    execute format('grant select, insert, update on public.%I to authenticated', t);
    execute format('grant all on public.%I to service_role', t);
  end loop;
end $$;

-- Views inherit the RLS of their base tables when created by a non-superuser,
-- but the grant still has to exist.
grant select on public.po_line_status, public.part_current_cost,
                public.rebate_position to authenticated;

-- ── 12. seed — the supplier that exists in fact but not yet in data ────────
-- One brand, one supplier, one warehouse. Created without contact detail on
-- purpose: empty fields are honest and fillable, and waiting for them would
-- block work that does not depend on them.
insert into public.supplier (code, name, currency, notes)
values ('FAW', 'FAW Jiefang', 'ZAR',
        'Created by migration 0039. Currency and incoterm are defaults - set '
        'them when the real terms are known. Contact detail deliberately left '
        'blank rather than guessed.')
on conflict (code) do nothing;

commit;

-- ============================================================================
--  VERIFY BY QUERY — RAISE NOTICE is not surfaced by the Supabase SQL editor.
--
--  1. Thirteen new tables, all with RLS on:
--     select tablename, rowsecurity from pg_tables
--      where schemaname='public'
--        and tablename in ('supplier','purchase_order','purchase_order_line',
--            'goods_receipt','goods_receipt_line','receipt_cost',
--            'part_landed_cost','receipt_discrepancy','supplier_claim',
--            'rebate_agreement','rebate_agreement_scope','rebate_tier',
--            'rebate_accrual')
--      order by tablename;                       -- expect 13 rows, all true
--
--  2. Every part still has a cost, and it still comes from the price list
--     because no receipt has been posted yet:
--     select basis, count(*) from part_current_cost group by 1;
--     -- expect price_list 159, none 2
--
--  3. The two cost figures agree until a rebate settles, which is correct:
--     select count(*) from part_current_cost
--      where cost_invoiced_minor <> cost_expected_minor;   -- expect 0
--
--  4. The supplier seed:
--     select id, code, name, currency, incoterm from supplier;
--
--  5. touch_rev is now on the new tables too:
--     select event_object_table from information_schema.triggers
--      where trigger_name like '%_touch_rev' order by 1;   -- expect 34
-- ============================================================================
