-- ============================================================================
--  CTP Core — Postgres schema (server source of truth)
--  Ported from the SQLite migrations 0001–0009. Consolidated: every ALTER is
--  folded into the CREATE so this is the canonical server schema.
--  Apply into a fresh Supabase project (SQL editor or `psql`).
--
--  Conventions kept from the desktop app:
--   * money in INTEGER minor units (never float)
--   * append-only stock ledger; on-hand is DERIVED (never a stored qty)
--   * every business row carries sync columns: rev / updated_at / deleted_at / origin
--   * is_primary on callouts is a RANK (0,1,2…), not a boolean — kept INTEGER
--
--  PK choice: BIGINT identity, 1:1 with the existing SQLite ids so the one-time
--  data migration preserves all foreign keys. (NOTE: for heavy offline multi-
--  device CREATION later, consider UUID PKs on those tables — see server/README.)
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;   -- substring / part-number search

-- ─────────────────────────────────────────────────────────── taxonomy ──────
CREATE TABLE category (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id   BIGINT REFERENCES category(id),
  code        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  path        TEXT NOT NULL,
  rev         INTEGER NOT NULL DEFAULT 1,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ,
  origin      TEXT
);

CREATE TABLE brand (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  is_oem      INTEGER NOT NULL DEFAULT 0,
  rev         INTEGER NOT NULL DEFAULT 1,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ,
  origin      TEXT
);

-- ─────────────────────────────────────────────────────────── part ──────────
CREATE TABLE part (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku              TEXT NOT NULL UNIQUE,
  mpn              TEXT,
  brand_id         BIGINT REFERENCES brand(id),
  category_id      BIGINT NOT NULL REFERENCES category(id),
  name             TEXT NOT NULL,
  description      TEXT,
  uom              TEXT NOT NULL DEFAULT 'EA',
  weight_g         INTEGER,
  status           TEXT NOT NULL DEFAULT 'active'
                     CHECK (status IN ('active','superseded','discontinued')),
  superseded_by    BIGINT REFERENCES part(id),
  -- three-tier identity + media locator (was migration 0006)
  make             TEXT,
  model            TEXT,
  drawing_no       TEXT,
  diagram_item_no  INTEGER,
  locator          TEXT,
  catalogue_pn     TEXT,
  inventory_pn     TEXT,
  side             TEXT CHECK (side IN ('L','R','C','B') OR side IS NULL),
  -- import bookkeeping (was migration 0007)
  match_status     TEXT,
  notes            TEXT,
  -- editable ZAR list price (was migration 0009)
  list_price_minor INTEGER,
  rev              INTEGER NOT NULL DEFAULT 1,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at       TIMESTAMPTZ,
  origin           TEXT
);
CREATE INDEX part_category_idx    ON part(category_id);
CREATE INDEX part_brand_idx       ON part(brand_id);
CREATE UNIQUE INDEX part_locator_idx ON part(locator) WHERE locator IS NOT NULL;
CREATE INDEX part_catalogue_pn_idx ON part(catalogue_pn);
CREATE INDEX part_inventory_pn_idx ON part(inventory_pn);
CREATE INDEX part_make_model_idx   ON part(make, model);
-- server-side fuzzy / part-number search (the desktop keeps its own FTS5 trigram).
-- Covers the part's own identifiers; brand/xref search can join or be added to a
-- trigger-maintained body column later.
CREATE INDEX part_search_trgm ON part USING gin (
  (coalesce(sku,'')||' '||coalesce(mpn,'')||' '||coalesce(name,'')||' '||
   coalesce(locator,'')||' '||coalesce(catalogue_pn,'')||' '||coalesce(inventory_pn,''))
  gin_trgm_ops);

CREATE TABLE part_xref (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id     BIGINT NOT NULL REFERENCES part(id) ON DELETE CASCADE,
  xref_number TEXT NOT NULL,
  xref_brand  TEXT,
  xref_type   TEXT NOT NULL CHECK (xref_type IN ('oem','aftermarket','competitor','supersession')),
  confidence  INTEGER NOT NULL DEFAULT 100 CHECK (confidence BETWEEN 0 AND 100),
  rev         INTEGER NOT NULL DEFAULT 1,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ,
  origin      TEXT,
  UNIQUE (part_id, xref_number, xref_type)
);
CREATE INDEX xref_part_idx ON part_xref(part_id);

-- ──────────────────────────────────────────────── fitment / vehicles ───────
CREATE TABLE vehicle_model (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  make        TEXT NOT NULL,
  model       TEXT NOT NULL,
  variant     TEXT NOT NULL DEFAULT '',
  rev         INTEGER NOT NULL DEFAULT 1,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ,
  origin      TEXT,
  UNIQUE (make, model, variant)
);

CREATE TABLE part_fitment (
  part_id     BIGINT NOT NULL REFERENCES part(id) ON DELETE CASCADE,
  vehicle_id  BIGINT NOT NULL REFERENCES vehicle_model(id),
  engine      TEXT NOT NULL DEFAULT '',
  year_from   INTEGER,
  year_to     INTEGER,
  note        TEXT,
  rev         INTEGER NOT NULL DEFAULT 1,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ,
  origin      TEXT,
  PRIMARY KEY (part_id, vehicle_id, engine)
);
CREATE INDEX fitment_vehicle_idx ON part_fitment(vehicle_id);

-- ───────────────────────────────────────────── inventory (ledger) ──────────
CREATE TABLE location (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  rev         INTEGER NOT NULL DEFAULT 1,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ,
  origin      TEXT
);

-- APPEND-ONLY ledger. on-hand is SUM(delta). client_uuid makes posts idempotent
-- across offline devices — the spine of conflict-free multi-device sync.
CREATE TABLE stock_movement (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id     BIGINT NOT NULL REFERENCES part(id),
  location_id BIGINT NOT NULL REFERENCES location(id),
  delta       INTEGER NOT NULL CHECK (delta <> 0),
  reason      TEXT NOT NULL CHECK (reason IN ('receipt','sale','adjustment','transfer','return','count')),
  ref_type    TEXT,
  ref_id      BIGINT,
  actor_id    BIGINT,
  client_uuid TEXT NOT NULL UNIQUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  origin      TEXT
);
CREATE INDEX movement_part_loc_idx ON stock_movement(part_id, location_id);

CREATE TABLE stock_policy (
  part_id       BIGINT NOT NULL REFERENCES part(id) ON DELETE CASCADE,
  location_id   BIGINT NOT NULL REFERENCES location(id) ON DELETE CASCADE,
  bin           TEXT,
  reorder_point INTEGER,
  reorder_qty   INTEGER,
  rev           INTEGER NOT NULL DEFAULT 1,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at    TIMESTAMPTZ,
  origin        TEXT,
  PRIMARY KEY (part_id, location_id)
);

CREATE TABLE price (
  part_id      BIGINT NOT NULL REFERENCES part(id) ON DELETE CASCADE,
  tier         TEXT NOT NULL DEFAULT 'list' CHECK (tier IN ('list','trade','wholesale')),
  currency     TEXT NOT NULL DEFAULT 'USD',
  amount_minor INTEGER NOT NULL CHECK (amount_minor >= 0),
  valid_from   TIMESTAMPTZ NOT NULL DEFAULT now(),
  rev          INTEGER NOT NULL DEFAULT 1,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at   TIMESTAMPTZ,
  origin       TEXT,
  PRIMARY KEY (part_id, tier, currency, valid_from)
);

-- ─────────────────────────────────────────────── sales / CRM ───────────────
CREATE TABLE customer (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  contact     TEXT,
  phone       TEXT,
  email       TEXT,
  price_tier  TEXT NOT NULL DEFAULT 'list' CHECK (price_tier IN ('list','trade','wholesale')),
  notes       TEXT,
  -- link a customer record to a login (Supabase auth user) for the client portal
  auth_user_id UUID,
  rev         INTEGER NOT NULL DEFAULT 1,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ,
  origin      TEXT
);
CREATE INDEX customer_auth_idx ON customer(auth_user_id);

CREATE TABLE sales_order (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number       TEXT NOT NULL UNIQUE,
  customer_id  BIGINT NOT NULL REFERENCES customer(id),
  location_id  BIGINT NOT NULL REFERENCES location(id),
  status       TEXT NOT NULL DEFAULT 'quote'
                 CHECK (status IN ('quote','confirmed','fulfilled','invoiced','cancelled')),
  currency     TEXT NOT NULL DEFAULT 'USD',
  notes        TEXT,
  fulfilled_at TIMESTAMPTZ,
  tax_rate_bps INTEGER NOT NULL DEFAULT 0,     -- was migration 0004
  rev          INTEGER NOT NULL DEFAULT 1,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at   TIMESTAMPTZ,
  origin       TEXT
);
CREATE INDEX so_customer_idx ON sales_order(customer_id);
CREATE INDEX so_status_idx   ON sales_order(status);

CREATE TABLE sales_line (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id         BIGINT NOT NULL REFERENCES sales_order(id) ON DELETE CASCADE,
  part_id          BIGINT NOT NULL REFERENCES part(id),
  qty              INTEGER NOT NULL CHECK (qty > 0),
  unit_price_minor INTEGER NOT NULL CHECK (unit_price_minor >= 0),  -- snapshot
  tier_at_add      TEXT NOT NULL DEFAULT 'list',
  rev              INTEGER NOT NULL DEFAULT 1,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at       TIMESTAMPTZ,
  origin           TEXT,
  UNIQUE (order_id, part_id)
);
CREATE INDEX sl_order_idx ON sales_line(order_id);

-- ─────────────────────────────────────────── accounting outbox ─────────────
CREATE TABLE accounting_export (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    BIGINT NOT NULL REFERENCES sales_order(id),
  target      TEXT NOT NULL CHECK (target IN ('quickbooks','xero')),
  batch_uuid  TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'exported' CHECK (status IN ('exported','error')),
  external_ref TEXT,
  payload_hash TEXT,
  exported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  origin      TEXT,
  UNIQUE (order_id, target)
);
CREATE INDEX acct_export_target_idx ON accounting_export(target, exported_at);

-- ─────────────────────────────────────────── company letterhead ────────────
CREATE TABLE company (
  id          BIGINT PRIMARY KEY CHECK (id = 1),
  name        TEXT NOT NULL,
  address     TEXT,
  phone       TEXT,
  email       TEXT,
  tax_id      TEXT,
  currency    TEXT NOT NULL DEFAULT 'USD',
  terms       TEXT,
  rev         INTEGER NOT NULL DEFAULT 1,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  origin      TEXT
);

-- ─────────────────────────────────────────── diagrams & media ──────────────
CREATE TABLE diagram (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drawing_key   TEXT NOT NULL UNIQUE,
  title         TEXT NOT NULL,
  section_code  TEXT,
  make          TEXT,
  model         TEXT,
  image_path    TEXT,
  model_3d_path TEXT,
  source        TEXT,
  img_w         INTEGER,                -- was migration 0008 (hotspot scaling)
  img_h         INTEGER,
  rev           INTEGER NOT NULL DEFAULT 1,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at    TIMESTAMPTZ,
  origin        TEXT
);
CREATE INDEX diagram_make_model_idx ON diagram(make, model);

CREATE TABLE part_diagram_callout (
  part_id    BIGINT NOT NULL REFERENCES part(id) ON DELETE CASCADE,
  diagram_id BIGINT NOT NULL REFERENCES diagram(id) ON DELETE CASCADE,
  item_no    INTEGER NOT NULL,
  is_primary INTEGER NOT NULL DEFAULT 1,   -- RANK: his own=1 wins; rusauto ref=0
  rev        INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  origin     TEXT,
  PRIMARY KEY (part_id, diagram_id)
);
CREATE INDEX callout_diagram_idx ON part_diagram_callout(diagram_id, item_no);

CREATE TABLE part_image (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id    BIGINT NOT NULL REFERENCES part(id) ON DELETE CASCADE,
  path       TEXT NOT NULL,
  kind       TEXT NOT NULL DEFAULT 'photo' CHECK (kind IN ('photo','render','raw','thumb')),
  is_primary INTEGER NOT NULL DEFAULT 0,
  sort_order INTEGER NOT NULL DEFAULT 0,
  caption    TEXT,
  rev        INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  origin     TEXT
);
CREATE INDEX image_part_idx ON part_image(part_id, is_primary DESC, sort_order);

CREATE TABLE part_model (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id   BIGINT NOT NULL REFERENCES part(id) ON DELETE CASCADE,
  glb_path  TEXT NOT NULL,
  format    TEXT NOT NULL DEFAULT 'glb' CHECK (format IN ('glb','gltf','obj')),
  source    TEXT,
  rev       INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  origin    TEXT
);
CREATE INDEX model_part_idx ON part_model(part_id);

CREATE TABLE hotspot (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  diagram_id BIGINT NOT NULL REFERENCES diagram(id) ON DELETE CASCADE,
  part_id    BIGINT REFERENCES part(id) ON DELETE CASCADE,
  item_no    TEXT,
  x          DOUBLE PRECISION NOT NULL,   -- image-pixel coords (scale by img_w/h)
  y          DOUBLE PRECISION NOT NULL,
  radius     DOUBLE PRECISION NOT NULL DEFAULT 58,
  rev        INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  origin     TEXT
);
CREATE INDEX hotspot_diagram_idx ON hotspot(diagram_id);
CREATE INDEX hotspot_part_idx    ON hotspot(part_id);

-- ─────────────────────────────────────────── leads (NEW, public surface) ───
-- The public-website "Check price / Request a quote" capture. POPIA-first:
-- store the EXACT consent wording shown + when + from where, and an opt-out path.
CREATE TABLE lead (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             TEXT,
  company          TEXT,
  email            TEXT,
  phone            TEXT,
  part_id          BIGINT REFERENCES part(id),   -- which part triggered it (optional)
  part_ref         TEXT,                          -- free-text SKU/PN if no part_id
  message          TEXT,
  source           TEXT,                          -- 'part_panel_cta', 'contact_form', …
  marketing_consent  INTEGER NOT NULL DEFAULT 0,  -- 0/1
  consent_text     TEXT,                          -- exact wording the user agreed to
  consent_at       TIMESTAMPTZ,
  consent_ip       TEXT,
  opted_out_at     TIMESTAMPTZ,
  status           TEXT NOT NULL DEFAULT 'new'
                     CHECK (status IN ('new','contacted','qualified','converted','archived')),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  rev              INTEGER NOT NULL DEFAULT 1,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at       TIMESTAMPTZ,
  origin           TEXT
);
CREATE INDEX lead_status_idx ON lead(status, created_at);

-- ─────────────────────────────────────────── derived views ─────────────────
CREATE VIEW stock_on_hand AS
  SELECT part_id, location_id, SUM(delta) AS qty_on_hand
  FROM stock_movement GROUP BY part_id, location_id;

CREATE VIEW order_total AS
  SELECT order_id,
         SUM(qty)                    AS line_count,
         SUM(qty * unit_price_minor) AS subtotal_minor
  FROM sales_line
  WHERE deleted_at IS NULL
  GROUP BY order_id;

-- One-stop part card (mirrors the desktop part_detail view, migration 0009).
CREATE VIEW part_detail AS
SELECT
  p.id, p.sku, p.locator, p.name, p.description, p.side,
  p.make, p.model, p.drawing_no, p.diagram_item_no,
  p.catalogue_pn, p.inventory_pn, p.mpn, p.match_status, p.notes,
  p.list_price_minor,
  c.code AS category_code, c.name AS category_name,
  p.status,
  COALESCE((SELECT SUM(delta) FROM stock_movement WHERE part_id = p.id), 0) AS qty_on_hand,
  (SELECT bin FROM stock_policy WHERE part_id = p.id LIMIT 1) AS bin,
  (SELECT amount_minor FROM price WHERE part_id = p.id AND tier='list' AND currency='USD'
        ORDER BY valid_from DESC LIMIT 1) AS price_usd_minor,
  (SELECT amount_minor FROM price WHERE part_id = p.id AND tier='list' AND currency='ZAR'
        ORDER BY valid_from DESC LIMIT 1) AS price_zar_minor,
  (SELECT path FROM part_image WHERE part_id = p.id AND deleted_at IS NULL
        ORDER BY is_primary DESC, sort_order LIMIT 1) AS primary_image,
  (SELECT glb_path FROM part_model WHERE part_id = p.id AND deleted_at IS NULL LIMIT 1) AS model_3d,
  (SELECT d.image_path FROM part_diagram_callout pdc JOIN diagram d ON d.id = pdc.diagram_id
        WHERE pdc.part_id = p.id ORDER BY pdc.is_primary DESC LIMIT 1) AS diagram_image,
  (SELECT pdc.item_no FROM part_diagram_callout pdc
        WHERE pdc.part_id = p.id ORDER BY pdc.is_primary DESC LIMIT 1) AS diagram_item
FROM part p
JOIN category c ON c.id = p.category_id
WHERE p.deleted_at IS NULL;

-- End of schema. RLS + roles live in rls.sql (apply AFTER this file).
