// Web/PWA backend: PowerSync local SQLite for reads, Supabase for writes.
//
// STATUS: Tier 1 reads ported (lookup + Jefrey's catalogue). Commands are ported
// one at a time (see PORTED below); anything not yet ported throws a clear error
// rather than failing silently, so a half-ported build is obvious in the console
// instead of showing blanks.
//
// Ported:
//   Reads:  search_parts, part_detail, list_parts, list_categories,
//           list_locations, jefrey_catalogue, get_company
//   Writes: post_movement — the first write through the PowerSync upload path
//           (local INSERT → crud queue → SupabaseConnector → Postgres).
//
// Still to port:
//   Tier 1: jefrey_aliases (read), jefrey_learn / jefrey_forget (writes —
//     the upload path now exists; copy the post_movement pattern).
//   Tier 2 (counter): save_part_image
//   Tier 3 (sales):   list_customers, list_orders, get_order, create_order,
//     add_line, update_line_qty, remove_line, set_status, fulfill_order, set_tax_rate
//
// Desktop-only (never ported): the hotspot editor, save_diagram/delete_diagram,
// update_part, export_accounting, delete_part/restore_part, open_url.
//
// ⚠ COST PRICES — read this before adding any non-staff login.
// jefrey_catalogue.cost_minor and part_detail's ZAR cost now return REAL landed
// cost (they were null while part_cost was unsynced). That is correct for staff
// on a phone and wrong for anything customer-facing.
//
// The important part: migration 0015 locked part_cost and price_tier to staff
// over the Data API, but PowerSync replicates as `powersync_role`, which
// BYPASSES RLS. The only thing keeping cost off a device is which sync stream
// that device subscribes to — see `ctp_staff` in server/sync-streams.yaml. A
// customer account created today would sync full cost to their phone. Gate
// `ctp_staff` on the user_role claim before any such account exists, and never
// rely on the UI to hide these fields.
//
// ── Two things worth knowing before you read the SQL ──────────────────────────
//
// 1. The Rust layer reads through the `part_detail` VIEW and the `part_search`
//    FTS5 table. Neither exists in the PowerSync schema — PowerSync only mirrors
//    base tables. So the view is re-expressed inline as PART_DETAIL_SQL below,
//    column-for-column against migration 0013's definition, and the FTS index is
//    replaced by a scan (see searchParts).
//
// 2. Ids are integers on the desktop and text in PowerSync. The Postgres schema
//    kept the original integer ids (BIGINT GENERATED BY DEFAULT AS IDENTITY, and
//    migrate_sqlite_to_pg.py preserves every id), so a PowerSync id is the string
//    form of the same number and Number(id) round-trips it. numId() below asserts
//    that, so if ids ever become UUIDs this fails loudly instead of quietly
//    returning part 0.
import type { Backend } from "./backend";
import { makeUuid } from "./uuid";
import { powerSync } from "../sync/system";

type Row = Record<string, unknown>;
type Handler = (args: Record<string, unknown>) => Promise<unknown>;

// ─── plumbing ────────────────────────────────────────────────────────────────

let readyOnce: Promise<void> | null = null;
/** PowerSync must be open before any read. Safe to call on every query. */
function ready(): Promise<void> {
  if (!readyOnce) readyOnce = powerSync.init();
  return readyOnce;
}

async function all<T = Row>(sql: string, params: unknown[] = []): Promise<T[]> {
  await ready();
  return powerSync.getAll<T>(sql, params);
}

async function one<T = Row>(sql: string, params: unknown[] = []): Promise<T | null> {
  await ready();
  return powerSync.getOptional<T>(sql, params);
}

/**
 * A PowerSync text id as the integer the UI expects. Throws rather than
 * returning a wrong-but-plausible id: every view types partId as `number`, so a
 * silent 0 here would surface as "part not found" three layers away.
 */
function numId(v: unknown, what = "id"): number {
  const n = Number(v);
  if (!Number.isInteger(n)) {
    throw new Error(
      `[CTP web] ${what} "${String(v)}" is not an integer id. The desktop UI ` +
        `indexes parts by integer id; if the backend moved to UUIDs, the data ` +
        `seam (src/data) needs to carry string ids end to end.`
    );
  }
  return n;
}

const bool = (v: unknown): boolean => Number(v) !== 0;
const str = (v: unknown): string => (v == null ? "" : String(v));
const nstr = (v: unknown): string | null => (v == null || v === "" ? null : String(v));
const nnum = (v: unknown): number | null => (v == null ? null : Number(v));

// ─── the part_detail view, re-expressed ──────────────────────────────────────
// Mirrors migrations/0013_pricing_reset.sql's CREATE VIEW part_detail — the
// current definition, column for column, with no gaps.
//
// It used to have two holes (diagram_item and the ZAR cost), both because the
// backing columns had not reached Postgres or the sync config. Postgres 0016
// landed the data (122 diagram_refs, 159 part_cost rows) and part_cost is now
// carried by the `ctp_staff` sync stream, so both are read for real below.
const PART_DETAIL_SQL = `
  SELECT
    p.id                AS id,
    p.sku               AS sku,
    p.locator           AS locator,
    p.name              AS name,
    p.description       AS description,
    p.side              AS side,
    p.make              AS make,
    p.model             AS model,
    p.drawing_no        AS drawing_no,
    p.diagram_item_no   AS diagram_item_no,
    p.catalogue_pn      AS catalogue_pn,
    p.inventory_pn      AS inventory_pn,
    p.mpn               AS mpn,
    c.code              AS category_code,
    c.name              AS category_name,
    p.status            AS status,
    p.match_status      AS match_status,
    p.notes             AS notes,
    p.list_price_minor  AS list_price_minor,
    COALESCE((SELECT SUM(m.delta) FROM stock_movement m WHERE m.part_id = p.id), 0) AS qty_on_hand,
    (SELECT sp.bin FROM stock_policy sp WHERE sp.part_id = p.id LIMIT 1) AS bin,
    -- Migration 0013 moved landed cost out of the price table (where it sat
    -- mislabelled as tier='list') into part_cost, and made tier='list' the
    -- real list price. USD cost is no longer tracked, so price_usd_minor is
    -- NULL by definition — not a gap. Matches the view exactly.
    NULL                AS price_usd_minor,
    -- Landed COST, newest shipment first. Despite the column name this is what
    -- the view calls price_zar_minor and what Jefrey reads as cost_minor.
    -- part_cost is versioned by valid_from, so ORDER BY matters: without it a
    -- reprice would return whichever historical row SQLite happened to hit.
    (SELECT pc.amount_minor FROM part_cost pc
      WHERE pc.part_id = p.id AND pc.currency = 'ZAR' AND pc.deleted_at IS NULL
      ORDER BY pc.valid_from DESC LIMIT 1) AS price_zar_minor,
    (SELECT pi.path FROM part_image pi
      WHERE pi.part_id = p.id AND pi.deleted_at IS NULL
      ORDER BY pi.is_primary DESC, pi.sort_order LIMIT 1) AS primary_image,
    (SELECT pm.glb_path FROM part_model pm
      WHERE pm.part_id = p.id AND pm.deleted_at IS NULL LIMIT 1) AS model_3d,
    (SELECT d.image_path FROM diagram d
      WHERE d.drawing_key = 'SEC' || p.category_id LIMIT 1) AS diagram_image,
    p.diagram_ref       AS diagram_item
  FROM part p
  JOIN category c ON c.id = p.category_id
  WHERE p.deleted_at IS NULL
`;

/**
 * Fields the browser build cannot fill yet, and why. Logged once per session so
 * a missing value in the UI is explained in the console instead of looking like
 * a bug in the query.
 */
// Verified against Postgres on 2026-08-06: 161/161 live parts resolve to a SEC*
// section view and 122 carry a diagram_ref, so the DATA gaps are closed. What
// remains is not data.
const GAPS = [
  "image + diagram + .glb PATHS resolve to /assets/… which only exists in the " +
    "desktop bundle. A hosted web build 404s every one until the files move to " +
    "Supabase Storage and an assetUrl() resolver lands (mobile plan M2)",
  "jefrey_learn / jefrey_forget — part_alias syncs now, but these are WRITES " +
    "and the PowerSync upload path is not ported yet (M0.3)",
];
let gapsLogged = false;
function noteGaps(): void {
  if (gapsLogged) return;
  gapsLogged = true;
  console.info("[CTP web] known data gaps in this build:\n  - " + GAPS.join("\n  - "));
}

// ─── search: a scan, not an FTS index ────────────────────────────────────────
//
// The desktop ranks by bm25 over an FTS5 trigram index built from
//   sku · mpn · name · locator · catalogue_pn · inventory_pn · brand.name · every xref
// (see migrations 0006/0012). PowerSync mirrors base tables only — there is no
// FTS index to query — so this scans the same field set with instr() and ranks
// in JS. At 173 live parts that is well under a frame; if the catalogue grows an
// order of magnitude, revisit with a client-side FTS5 table kept current by a
// PowerSync watch.
//
// The one honest behavioural difference: ordering. bm25 is a relevance score
// this cannot reproduce, so results are ranked by match specificity instead
// (exact identifier > prefix > substring > xref > name > brand only), tie-broken
// by shorter field then SKU. Same result SET as the desktop, sometimes a
// different order within it.
//
// Parity detail worth keeping: Rust guards on `query.trim().len() < 2`, but the
// index is `tokenize = 'trigram'`, so a 2-character MATCH finds nothing anyway.
// The effective desktop floor is 3, which is what this uses.

const MIN_QUERY = 3;

const SEARCH_SQL = `
  SELECT
    p.id, p.sku, p.name, p.mpn, p.locator, p.catalogue_pn, p.inventory_pn,
    b.name AS brand,
    COALESCE((SELECT SUM(m.delta) FROM stock_movement m WHERE m.part_id = p.id), 0) AS on_hand,
    -- Was ORDER BY (currency <> 'USD') first, preferring a USD row. Migration
    -- 0013 deleted every USD price and stopped tracking USD, so that tiebreak
    -- is dead code that would silently prefer a stale currency if one ever came
    -- back. Newest list price wins, full stop. deleted_at guard added to match
    -- the fallback in partDetail().
    (SELECT pr.amount_minor FROM price pr
      WHERE pr.part_id = p.id AND pr.tier = 'list' AND pr.deleted_at IS NULL
      ORDER BY pr.valid_from DESC LIMIT 1) AS price_cents,
    -- The two extra columns the mobile cards need. The desktop Hit type does
    -- not carry them (Rust search_parts predates the mobile shell); extra
    -- fields on a returned row are invisible to callers that don't read them.
    (SELECT sp.bin FROM stock_policy sp WHERE sp.part_id = p.id LIMIT 1) AS bin,
    (SELECT pi.path FROM part_image pi
      WHERE pi.part_id = p.id AND pi.deleted_at IS NULL
      ORDER BY pi.is_primary DESC, pi.sort_order LIMIT 1) AS thumb,
    (SELECT x.xref_type || ' # ' || x.xref_number FROM part_xref x
      WHERE x.part_id = p.id AND instr(lower(x.xref_number), ?) > 0 LIMIT 1) AS matched_xref,
    (SELECT group_concat(x2.xref_number || ' ' || COALESCE(x2.xref_brand, ''), ' ')
      FROM part_xref x2 WHERE x2.part_id = p.id) AS xref_body
  FROM part p
  LEFT JOIN brand b ON b.id = p.brand_id
  WHERE p.deleted_at IS NULL
    AND (
         instr(lower(p.sku), ?) > 0
      OR instr(lower(COALESCE(p.mpn, '')), ?) > 0
      OR instr(lower(p.name), ?) > 0
      OR instr(lower(COALESCE(p.locator, '')), ?) > 0
      OR instr(lower(COALESCE(p.catalogue_pn, '')), ?) > 0
      OR instr(lower(COALESCE(p.inventory_pn, '')), ?) > 0
      OR instr(lower(COALESCE(b.name, '')), ?) > 0
      OR EXISTS (SELECT 1 FROM part_xref x3
                  WHERE x3.part_id = p.id
                    AND (instr(lower(x3.xref_number), ?) > 0
                      OR instr(lower(COALESCE(x3.xref_brand, '')), ?) > 0))
    )
`;

/** Identifier fields, most specific first — this order drives the ranking. */
const ID_FIELDS = ["sku", "inventory_pn", "catalogue_pn", "locator", "mpn"] as const;

/** Lower is better. Mirrors "how directly did this row match?". */
function score(row: Row, term: string): [number, number, string] {
  const idVals = ID_FIELDS.map((f) => str(row[f]).toLowerCase()).filter(Boolean);
  const xrefs = str(row["xref_body"]).toLowerCase();
  const name = str(row["name"]).toLowerCase();

  let tier = 5; // brand-only match, or nothing more specific
  let width = 999;

  for (const v of idVals) {
    if (v === term) { tier = Math.min(tier, 0); width = Math.min(width, v.length); }
    else if (v.startsWith(term)) { tier = Math.min(tier, 1); width = Math.min(width, v.length); }
    else if (v.includes(term)) { tier = Math.min(tier, 2); width = Math.min(width, v.length); }
  }
  if (tier > 2 && xrefs.includes(term)) { tier = 3; width = Math.min(width, xrefs.length); }
  if (tier > 3 && name.includes(term)) { tier = 4; width = Math.min(width, name.length); }

  return [tier, width, str(row["sku"])];
}

async function searchParts(query: string): Promise<unknown[]> {
  const term = query.trim().toLowerCase();
  if (term.length < MIN_QUERY) return [];

  // 1 binding for matched_xref + 9 in the WHERE clause = 10 copies of the term.
  const rows = await all(SEARCH_SQL, Array(10).fill(term));

  const ranked = rows
    .map((r) => ({ r, k: score(r, term) }))
    .sort((a, b) => a.k[0] - b.k[0] || a.k[1] - b.k[1] || a.k[2].localeCompare(b.k[2]))
    .slice(0, 50);

  return ranked.map(({ r }) => {
    const sku = str(r["sku"]);
    // Explain WHY it matched, exactly as Rust does: a matching xref wins, then
    // locator / inventory # / catalogue #, else fall back to the SKU. A name-only
    // or mpn-only hit falls through to "part <sku>" on the desktop too — that is
    // parity, not an omission.
    let matched_on = nstr(r["matched_xref"]);
    if (!matched_on) {
      if (str(r["locator"]).toLowerCase().includes(term)) {
        matched_on = `locator ${str(r["locator"])}`;
      } else if (str(r["inventory_pn"]).toLowerCase().includes(term)) {
        matched_on = `inventory # ${str(r["inventory_pn"])}`;
      } else if (str(r["catalogue_pn"]).toLowerCase().includes(term)) {
        matched_on = `catalogue # ${str(r["catalogue_pn"])}`;
      }
    }
    return {
      id: numId(r["id"], "part.id"),
      sku,
      name: str(r["name"]),
      brand: nstr(r["brand"]),
      on_hand: Number(r["on_hand"]),
      price_cents: nnum(r["price_cents"]),
      matched_on: matched_on ?? `part ${sku}`,
      bin: nstr(r["bin"]),
      thumb: nstr(r["thumb"]),
    };
  });
}

// ─── part detail ─────────────────────────────────────────────────────────────

async function partDetail(partId: number): Promise<unknown> {
  noteGaps();
  const pid = String(partId);
  const d = await one(`SELECT * FROM (${PART_DETAIL_SQL}) WHERE id = ?`, [pid]);
  if (!d) throw new Error(`[CTP web] part ${partId} not found (or soft-deleted).`);

  const brand = await one<Row>(
    `SELECT b.name AS brand FROM part p LEFT JOIN brand b ON b.id = p.brand_id WHERE p.id = ?`,
    [pid]
  );

  const images = await all(
    `SELECT id, path, kind, is_primary FROM part_image
      WHERE part_id = ? AND deleted_at IS NULL
      ORDER BY is_primary DESC, sort_order`,
    [pid]
  );

  // Every location, left-joined, so empty ones still show a 0 line.
  const stock = await all(
    `SELECT l.id, l.code, l.name,
            COALESCE((SELECT SUM(m.delta) FROM stock_movement m
                       WHERE m.location_id = l.id AND m.part_id = ?), 0) AS on_hand,
            sp.bin, sp.reorder_point, sp.reorder_qty
       FROM location l
       LEFT JOIN stock_policy sp ON sp.location_id = l.id AND sp.part_id = ?
      WHERE l.deleted_at IS NULL
      ORDER BY CAST(l.id AS INTEGER)`,
    [pid, pid]
  );

  // Order by timestamp, not id. Locally-posted movements carry a UUID id until
  // the server acknowledges them and syncs back the bigint row; CAST(uuid AS
  // INTEGER) is 0, which would pin every fresh movement to the BOTTOM of the
  // ledger — exactly the row the person is looking for.
  const ledger = await all(
    `SELECT m.id, l.code AS location_code, m.delta, m.reason, m.created_at
       FROM stock_movement m JOIN location l ON l.id = m.location_id
      WHERE m.part_id = ?
      ORDER BY m.created_at DESC, m.id DESC LIMIT 25`,
    [pid]
  );

  // Rust: COALESCE(price_usd_minor, latest tier='list' in any currency).
  let priceCents = nnum(d["price_usd_minor"]);
  if (priceCents == null) {
    const fallback = await one<Row>(
      `SELECT amount_minor FROM price WHERE part_id = ? AND tier = 'list'
        AND deleted_at IS NULL ORDER BY valid_from DESC LIMIT 1`,
      [pid]
    );
    priceCents = nnum(fallback?.["amount_minor"]);
  }

  const stockLines = stock.map((s) => ({
    location_id: numId(s["id"], "location.id"),
    location_code: str(s["code"]),
    location_name: str(s["name"]),
    on_hand: Number(s["on_hand"]),
    bin: nstr(s["bin"]),
    reorder_point: nnum(s["reorder_point"]),
    reorder_qty: nnum(s["reorder_qty"]),
  }));

  return {
    id: numId(d["id"], "part.id"),
    sku: str(d["sku"]),
    locator: nstr(d["locator"]),
    catalogue_pn: nstr(d["catalogue_pn"]),
    inventory_pn: nstr(d["inventory_pn"]),
    mpn: nstr(d["mpn"]),
    name: str(d["name"]),
    side: nstr(d["side"]),
    make: nstr(d["make"]),
    model: nstr(d["model"]),
    drawing_no: nstr(d["drawing_no"]),
    diagram_item_no: nnum(d["diagram_item_no"]),
    category_code: nstr(d["category_code"]),
    category_name: nstr(d["category_name"]),
    match_status: nstr(d["match_status"]),
    notes: nstr(d["notes"]),
    status: nstr(d["status"]),
    brand: nstr(brand?.["brand"]),
    description: nstr(d["description"]),
    price_cents: priceCents,
    list_price_minor: nnum(d["list_price_minor"]),
    total_on_hand: stockLines.reduce((t, s) => t + s.on_hand, 0),
    stock: stockLines,
    // numId() would THROW on the UUID a locally-posted movement carries before
    // its round-trip — taking the whole part sheet down for the seconds (or
    // offline hours) the row sits in the upload queue. Ledger ids are display
    // keys, nothing more, so an unsynced row gets a stable negative stand-in.
    ledger: ledger.map((m, i) => {
      const n = Number(m["id"]);
      return {
        id: Number.isInteger(n) ? n : -(i + 1),
        location_code: str(m["location_code"]),
        delta: Number(m["delta"]),
        reason: str(m["reason"]),
        created_at: str(m["created_at"]),
      };
    }),
    images: images.map((i) => ({
      id: numId(i["id"], "part_image.id"),
      path: str(i["path"]),
      kind: str(i["kind"]),
      is_primary: bool(i["is_primary"]),
    })),
    diagram_image: nstr(d["diagram_image"]),
    diagram_item: nstr(d["diagram_item"]),
    model_3d: nstr(d["model_3d"]),
  };
}

// ─── flat lists ──────────────────────────────────────────────────────────────

async function listParts(): Promise<unknown[]> {
  noteGaps();
  // price_cents used to read price_usd_minor, which this file defines as a
  // literal NULL — so every row in the Parts table showed a blank price. The
  // desktop's list_parts COALESCEs USD onto the latest tier='list' row, so the
  // correct source post-0013 is simply the list price. Selected alongside the
  // view rather than inside it, because part_detail has no such column.
  const rows = await all(
    `SELECT v.*,
            (SELECT pr.amount_minor FROM price pr
              WHERE pr.part_id = v.id AND pr.tier = 'list' AND pr.deleted_at IS NULL
              ORDER BY pr.valid_from DESC LIMIT 1) AS list_row_minor
       FROM (${PART_DETAIL_SQL}) v
      ORDER BY v.category_code, v.sku`
  );
  return rows.map((r) => ({
    id: numId(r["id"], "part.id"),
    sku: str(r["sku"]),
    locator: nstr(r["locator"]),
    name: str(r["name"]),
    side: nstr(r["side"]),
    category_code: nstr(r["category_code"]),
    catalogue_pn: nstr(r["catalogue_pn"]),
    inventory_pn: nstr(r["inventory_pn"]),
    status: nstr(r["status"]),
    match_status: nstr(r["match_status"]),
    qty_on_hand: Number(r["qty_on_hand"]),
    bin: nstr(r["bin"]),
    price_cents: nnum(r["list_row_minor"]) ?? nnum(r["list_price_minor"]),
    // The mobile cards want the actual thumbnail path, not just the boolean.
    // Desktop list_parts has no such field; extra fields are invisible to it.
    image: nstr(r["primary_image"]),
    has_photo: r["primary_image"] != null,
    has_diagram: r["diagram_image"] != null,
    has_model: r["model_3d"] != null,
  }));
}

async function jefreyCatalogue(): Promise<unknown[]> {
  noteGaps();
  const rows = await all(`SELECT * FROM (${PART_DETAIL_SQL}) ORDER BY CAST(id AS INTEGER)`);
  return rows.map((r) => ({
    id: numId(r["id"], "part.id"),
    sku: str(r["sku"]),
    name: str(r["name"]),
    side: nstr(r["side"]),
    inv_pn: nstr(r["inventory_pn"]),
    cat_pn: nstr(r["catalogue_pn"]),
    locator: nstr(r["locator"]),
    section: nstr(r["category_name"]),
    loc: nstr(r["bin"]),
    qty: Number(r["qty_on_hand"]),
    cost_minor: nnum(r["price_zar_minor"]),
    list_minor: nnum(r["list_price_minor"]),
    dwg: nstr(r["drawing_no"]),
    has_photo: r["primary_image"] != null,
    notes: nstr(r["notes"]),
    match_status: nstr(r["match_status"]),
  }));
}

async function listCategories(): Promise<unknown[]> {
  const rows = await all(
    `SELECT id, code, name FROM category WHERE deleted_at IS NULL ORDER BY code`
  );
  return rows.map((r) => ({
    id: numId(r["id"], "category.id"),
    code: str(r["code"]),
    name: str(r["name"]),
  }));
}

async function listLocations(): Promise<unknown[]> {
  const rows = await all(
    `SELECT id, code, name FROM location WHERE deleted_at IS NULL ORDER BY CAST(id AS INTEGER)`
  );
  return rows.map((r) => ({
    id: numId(r["id"], "location.id"),
    code: str(r["code"]),
    name: str(r["name"]),
  }));
}

async function getCompany(): Promise<unknown> {
  // Rust reads `WHERE id=1`; there is only ever one company row.
  const c =
    (await one(`SELECT name, address, phone, email, tax_id, currency, terms
                 FROM company WHERE id = '1'`)) ??
    (await one(`SELECT name, address, phone, email, tax_id, currency, terms
                 FROM company LIMIT 1`));
  if (!c) throw new Error("[CTP web] no company row has synced yet.");
  return {
    name: str(c["name"]),
    address: nstr(c["address"]),
    phone: nstr(c["phone"]),
    email: nstr(c["email"]),
    tax_id: nstr(c["tax_id"]),
    currency: str(c["currency"]),
    terms: nstr(c["terms"]),
  };
}

// ─── the first write: post_movement ──────────────────────────────────────────
//
// Mirrors the Rust command's contract exactly:
//   * sign policy lives HERE, not in the UI: receipt/return force +|delta|,
//     sale forces -|delta|, adjustment takes the delta as given. A UI bug can
//     therefore never book a sale that ADDS stock.
//   * zero-delta movements are refused — an empty ledger row is noise.
//   * client_uuid is the idempotency key. The row is INSERTed locally with a
//     generated UUID id; PowerSync queues it, SupabaseConnector uploads it
//     WITHOUT that id (Postgres assigns the bigint identity) and with
//     ON CONFLICT (client_uuid) DO NOTHING, so a retry after a dropped
//     connection can never double-book stock. The ledger is append-only —
//     mistakes are corrected by posting the inverse, never by editing.
//
// Reads pick the local row up instantly (on_hand is SUM(delta) over the local
// table), so the UI updates offline and the sync happens when it happens.
const MOVEMENT_REASONS = ["receipt", "sale", "return", "adjustment"] as const;

async function postMovement(a: Record<string, unknown>): Promise<unknown> {
  const partId = numId(a["partId"], "partId");
  const locationId = numId(a["locationId"], "locationId");
  const raw = Number(a["delta"]);
  const reason = str(a["reason"]);
  const clientUuid = str(a["clientUuid"]);
  const actorId = a["actorId"] == null ? null : String(a["actorId"]);

  if (!Number.isInteger(raw) || raw === 0) {
    throw new Error(`[CTP web] post_movement: delta must be a non-zero integer, got "${String(a["delta"])}".`);
  }
  if (!(MOVEMENT_REASONS as readonly string[]).includes(reason)) {
    throw new Error(`[CTP web] post_movement: reason "${reason}" is not one of ${MOVEMENT_REASONS.join("/")}.`);
  }
  if (!clientUuid) {
    throw new Error("[CTP web] post_movement: clientUuid is required (it is the idempotency key).");
  }

  const delta =
    reason === "sale" ? -Math.abs(raw)
    : reason === "receipt" || reason === "return" ? Math.abs(raw)
    : raw;

  await ready();
  await powerSync.execute(
    `INSERT INTO stock_movement (id, part_id, location_id, delta, reason, client_uuid, actor_id, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      makeUuid(),
      String(partId),
      String(locationId),
      delta,
      reason,
      clientUuid,
      actorId,
      new Date().toISOString(),
    ]
  );
  return delta;
}

// ─── registry ────────────────────────────────────────────────────────────────

const PORTED: Record<string, Handler> = {
  search_parts: (a) => searchParts(String(a["query"] ?? "")),
  part_detail: (a) => partDetail(Number(a["partId"])),
  list_parts: () => listParts(),
  list_categories: () => listCategories(),
  list_locations: () => listLocations(),
  jefrey_catalogue: () => jefreyCatalogue(),
  get_company: () => getCompany(),
  post_movement: (a) => postMovement(a),
};

export const webBackend: Backend = {
  async call<T>(cmd: string, args?: Record<string, unknown>): Promise<T> {
    const handler = PORTED[cmd];
    if (!handler) {
      throw new Error(
        `[CTP web] "${cmd}" is not available in the browser build yet. ` +
          `It still lives in the Rust layer — port it in src/data/backend.web.ts.`
      );
    }
    return (await handler(args ?? {})) as T;
  },
};

/** True when a command works in the browser build. Use to hide desktop-only UI on mobile. */
export function isPortedToWeb(cmd: string): boolean {
  return cmd in PORTED;
}
