// Web/PWA backend: PowerSync local SQLite for reads, Supabase for writes.
//
// STATUS: Tier 1 reads ported (lookup + Jefrey's catalogue). Commands are ported
// one at a time (see PORTED below); anything not yet ported throws a clear error
// rather than failing silently, so a half-ported build is obvious in the console
// instead of showing blanks.
//
// Ported (Tier 1 reads):
//   search_parts, part_detail, list_parts, list_categories, list_locations,
//   jefrey_catalogue, get_company
//
// Still to port:
//   Tier 1: jefrey_aliases (read), jefrey_learn / jefrey_forget (writes).
//     BLOCKED: part_alias is not in server/sync-streams.yaml, so the learned
//     vocabulary never reaches the client. That is mobile-plan item M0.3.
//   Tier 2 (counter): post_movement, save_part_image
//   Tier 3 (sales):   list_customers, list_orders, get_order, create_order,
//     add_line, update_line_qty, remove_line, set_status, fulfill_order, set_tax_rate
//
// Desktop-only (never ported): the hotspot editor, save_diagram/delete_diagram,
// update_part, export_accounting, delete_part/restore_part, open_url.
//
// ⚠ COST PRICES. Everything here runs with the signed-in user's full read scope.
// jefrey_catalogue exposes cost_minor and part_detail exposes price_cents. That
// is correct for staff on a phone and WRONG for a customer-facing surface. If
// this backend is ever reused for a client portal, the price fields need a
// role-scoped variant — do not rely on the UI to hide them.
//
// ── Two things worth knowing before you read the SQL ──────────────────────────
//
// 1. The Rust layer reads through the `part_detail` VIEW and the `part_search`
//    FTS5 table. Neither exists in the PowerSync schema — PowerSync only mirrors
//    base tables. So the view is re-expressed inline as PART_DETAIL_SQL below,
//    column-for-column against migration 0010's definition, and the FTS index is
//    replaced by a scan (see searchParts).
//
// 2. Ids are integers on the desktop and text in PowerSync. The Postgres schema
//    kept the original integer ids (BIGINT GENERATED BY DEFAULT AS IDENTITY, and
//    migrate_sqlite_to_pg.py preserves every id), so a PowerSync id is the string
//    form of the same number and Number(id) round-trips it. numId() below asserts
//    that, so if ids ever become UUIDs this fails loudly instead of quietly
//    returning part 0.
import type { Backend } from "./backend";
import { powerSync } from "../sync/system";

type Row = Record<string, unknown>;
type Handler = (args: Record<string, unknown>) => Promise<unknown>;

// ─── plumbing ────────────────────────────────────────────────────────────────

let readyOnce: Promise<void> | null = null;
/** PowerSync must be open before any read. Safe to call on every query. */
function ready(): Promise<void> {
  if (!readyOnce) readyOnce = powerSync.init();
  return readyOnce;
}

async function all<T = Row>(sql: string, params: unknown[] = []): Promise<T[]> {
  await ready();
  return powerSync.getAll<T>(sql, params);
}

async function one<T = Row>(sql: string, params: unknown[] = []): Promise<T | null> {
  await ready();
  return powerSync.getOptional<T>(sql, params);
}

/**
 * A PowerSync text id as the integer the UI expects. Throws rather than
 * returning a wrong-but-plausible id: every view types partId as `number`, so a
 * silent 0 here would surface as "part not found" three layers away.
 */
function numId(v: unknown, what = "id"): number {
  const n = Number(v);
  if (!Number.isInteger(n)) {
    throw new Error(
      `[CTP web] ${what} "${String(v)}" is not an integer id. The desktop UI ` +
        `indexes parts by integer id; if the backend moved to UUIDs, the data ` +
        `seam (src/data) needs to carry string ids end to end.`
    );
  }
  return n;
}

const bool = (v: unknown): boolean => Number(v) !== 0;
const str = (v: unknown): string => (v == null ? "" : String(v));
const nstr = (v: unknown): string | null => (v == null || v === "" ? null : String(v));
const nnum = (v: unknown): number | null => (v == null ? null : Number(v));

// ─── the part_detail view, re-expressed ──────────────────────────────────────
// Mirrors migrations/0010_section_diagrams.sql's CREATE VIEW part_detail, with
// one documented gap: `diagram_item` there is `p.diagram_ref`, a column added by
// migration 0010 that is NOT in src/sync/AppSchema.ts (nor in Postgres, which is
// still at 0009). It is selected as NULL here and flagged by GAPS below.
const PART_DETAIL_SQL = `
  SELECT
    p.id                AS id,
    p.sku               AS sku,
    p.locator           AS locator,
    p.name              AS name,
    p.description       AS description,
    p.side              AS side,
    p.make              AS make,
    p.model             AS model,
    p.drawing_no        AS drawing_no,
    p.diagram_item_no   AS diagram_item_no,
    p.catalogue_pn      AS catalogue_pn,
    p.inventory_pn      AS inventory_pn,
    p.mpn               AS mpn,
    c.code              AS category_code,
    c.name              AS category_name,
    p.status            AS status,
    p.match_status      AS match_status,
    p.notes             AS notes,
    p.list_price_minor  AS list_price_minor,
    COALESCE((SELECT SUM(m.delta) FROM stock_movement m WHERE m.part_id = p.id), 0) AS qty_on_hand,
    (SELECT sp.bin FROM stock_policy sp WHERE sp.part_id = p.id LIMIT 1) AS bin,
    -- Migration 0013 moved landed cost out of the price table (where it sat
    -- mislabelled as tier='list') into part_cost, and made tier='list' the
    -- real list price. USD cost is no longer tracked, so price_usd_minor is
    -- always NULL and price_cents falls through to the genuine list price.
    NULL                AS price_usd_minor,
    -- part_cost is not in AppSchema/sync-streams yet, so cost cannot reach the
    -- browser build. Jefrey's cost_minor stays null on web until it is. See GAPS.
    NULL                AS price_zar_minor,
    (SELECT pi.path FROM part_image pi
      WHERE pi.part_id = p.id AND pi.deleted_at IS NULL
      ORDER BY pi.is_primary DESC, pi.sort_order LIMIT 1) AS primary_image,
    (SELECT pm.glb_path FROM part_model pm
      WHERE pm.part_id = p.id AND pm.deleted_at IS NULL LIMIT 1) AS model_3d,
    (SELECT d.image_path FROM diagram d
      WHERE d.drawing_key = 'SEC' || p.category_id LIMIT 1) AS diagram_image,
    NULL                AS diagram_item
  FROM part p
  JOIN category c ON c.id = p.category_id
  WHERE p.deleted_at IS NULL
`;

/**
 * Fields the browser build cannot fill yet, and why. Logged once per session so
 * a missing value in the UI is explained in the console instead of looking like
 * a bug in the query.
 */
const GAPS = [
  "part_detail.diagram_item — needs part.diagram_ref in AppSchema + Postgres (migration 0010; mobile plan M0.2)",
  "part_detail.diagram_image — needs the SEC* diagram rows from migration 0010 to reach Postgres (M0.2)",
  "jefrey_aliases / jefrey_learn — needs part_alias in sync-streams.yaml (M0.3)",
  "jefrey_catalogue.cost_minor / part_detail cost — needs part_cost (migration 0013) in sync-streams.yaml + AppSchema",
];
let gapsLogged = false;
function noteGaps(): void {
  if (gapsLogged) return;
  gapsLogged = true;
  console.info("[CTP web] known data gaps in this build:\n  - " + GAPS.join("\n  - "));
}

// ─── search: a scan, not an FTS index ────────────────────────────────────────
//
// The desktop ranks by bm25 over an FTS5 trigram index built from
//   sku · mpn · name · locator · catalogue_pn · inventory_pn · brand.name · every xref
// (see migrations 0006/0012). PowerSync mirrors base tables only — there is no
// FTS index to query — so this scans the same field set with instr() and ranks
// in JS. At 173 live parts that is well under a frame; if the catalogue grows an
// order of magnitude, revisit with a client-side FTS5 table kept current by a
// PowerSync watch.
//
// The one honest behavioural difference: ordering. bm25 is a relevance score
// this cannot reproduce, so results are ranked by match specificity instead
// (exact identifier > prefix > substring > xref > name > brand only), tie-broken
// by shorter field then SKU. Same result SET as the desktop, sometimes a
// different order within it.
//
// Parity detail worth keeping: Rust guards on `query.trim().len() < 2`, but the
// index is `tokenize = 'trigram'`, so a 2-character MATCH finds nothing anyway.
// The effective desktop floor is 3, which is what this uses.

const MIN_QUERY = 3;

const SEARCH_SQL = `
  SELECT
    p.id, p.sku, p.name, p.mpn, p.locator, p.catalogue_pn, p.inventory_pn,
    b.name AS brand,
    COALESCE((SELECT SUM(m.delta) FROM stock_movement m WHERE m.part_id = p.id), 0) AS on_hand,
    (SELECT pr.amount_minor FROM price pr
      WHERE pr.part_id = p.id AND pr.tier = 'list'
      ORDER BY (pr.currency <> 'USD'), pr.valid_from DESC LIMIT 1) AS price_cents,
    (SELECT x.xref_type || ' # ' || x.xref_number FROM part_xref x
      WHERE x.part_id = p.id AND instr(lower(x.xref_number), ?) > 0 LIMIT 1) AS matched_xref,
    (SELECT group_concat(x2.xref_number || ' ' || COALESCE(x2.xref_brand, ''), ' ')
      FROM part_xref x2 WHERE x2.part_id = p.id) AS xref_body
  FROM part p
  LEFT JOIN brand b ON b.id = p.brand_id
  WHERE p.deleted_at IS NULL
    AND (
         instr(lower(p.sku), ?) > 0
      OR instr(lower(COALESCE(p.mpn, '')), ?) > 0
      OR instr(lower(p.name), ?) > 0
      OR instr(lower(COALESCE(p.locator, '')), ?) > 0
      OR instr(lower(COALESCE(p.catalogue_pn, '')), ?) > 0
      OR instr(lower(COALESCE(p.inventory_pn, '')), ?) > 0
      OR instr(lower(COALESCE(b.name, '')), ?) > 0
      OR EXISTS (SELECT 1 FROM part_xref x3
                  WHERE x3.part_id = p.id
                    AND (instr(lower(x3.xref_number), ?) > 0
                      OR instr(lower(COALESCE(x3.xref_brand, '')), ?) > 0))
    )
`;

/** Identifier fields, most specific first — this order drives the ranking. */
const ID_FIELDS = ["sku", "inventory_pn", "catalogue_pn", "locator", "mpn"] as const;

/** Lower is better. Mirrors "how directly did this row match?". */
function score(row: Row, term: string): [number, number, string] {
  const idVals = ID_FIELDS.map((f) => str(row[f]).toLowerCase()).filter(Boolean);
  const xrefs = str(row["xref_body"]).toLowerCase();
  const name = str(row["name"]).toLowerCase();

  let tier = 5; // brand-only match, or nothing more specific
  let width = 999;

  for (const v of idVals) {
    if (v === term) { tier = Math.min(tier, 0); width = Math.min(width, v.length); }
    else if (v.startsWith(term)) { tier = Math.min(tier, 1); width = Math.min(width, v.length); }
    else if (v.includes(term)) { tier = Math.min(tier, 2); width = Math.min(width, v.length); }
  }
  if (tier > 2 && xrefs.includes(term)) { tier = 3; width = Math.min(width, xrefs.length); }
  if (tier > 3 && name.includes(term)) { tier = 4; width = Math.min(width, name.length); }

  return [tier, width, str(row["sku"])];
}

async function searchParts(query: string): Promise<unknown[]> {
  const term = query.trim().toLowerCase();
  if (term.length < MIN_QUERY) return [];

  // 1 binding for matched_xref + 9 in the WHERE clause = 10 copies of the term.
  const rows = await all(SEARCH_SQL, Array(10).fill(term));

  const ranked = rows
    .map((r) => ({ r, k: score(r, term) }))
    .sort((a, b) => a.k[0] - b.k[0] || a.k[1] - b.k[1] || a.k[2].localeCompare(b.k[2]))
    .slice(0, 50);

  return ranked.map(({ r }) => {
    const sku = str(r["sku"]);
    // Explain WHY it matched, exactly as Rust does: a matching xref wins, then
    // locator / inventory # / catalogue #, else fall back to the SKU. A name-only
    // or mpn-only hit falls through to "part <sku>" on the desktop too — that is
    // parity, not an omission.
    let matched_on = nstr(r["matched_xref"]);
    if (!matched_on) {
      if (str(r["locator"]).toLowerCase().includes(term)) {
        matched_on = `locator ${str(r["locator"])}`;
      } else if (str(r["inventory_pn"]).toLowerCase().includes(term)) {
        matched_on = `inventory # ${str(r["inventory_pn"])}`;
      } else if (str(r["catalogue_pn"]).toLowerCase().includes(term)) {
        matched_on = `catalogue # ${str(r["catalogue_pn"])}`;
      }
    }
    return {
      id: numId(r["id"], "part.id"),
      sku,
      name: str(r["name"]),
      brand: nstr(r["brand"]),
      on_hand: Number(r["on_hand"]),
      price_cents: nnum(r["price_cents"]),
      matched_on: matched_on ?? `part ${sku}`,
    };
  });
}

// ─── part detail ─────────────────────────────────────────────────────────────

async function partDetail(partId: number): Promise<unknown> {
  noteGaps();
  const pid = String(partId);
  const d = await one(`SELECT * FROM (${PART_DETAIL_SQL}) WHERE id = ?`, [pid]);
  if (!d) throw new Error(`[CTP web] part ${partId} not found (or soft-deleted).`);

  const brand = await one<Row>(
    `SELECT b.name AS brand FROM part p LEFT JOIN brand b ON b.id = p.brand_id WHERE p.id = ?`,
    [pid]
  );

  const images = await all(
    `SELECT id, path, kind, is_primary FROM part_image
      WHERE part_id = ? AND deleted_at IS NULL
      ORDER BY is_primary DESC, sort_order`,
    [pid]
  );

  // Every location, left-joined, so empty ones still show a 0 line.
  const stock = await all(
    `SELECT l.id, l.code, l.name,
            COALESCE((SELECT SUM(m.delta) FROM stock_movement m
                       WHERE m.location_id = l.id AND m.part_id = ?), 0) AS on_hand,
            sp.bin, sp.reorder_point, sp.reorder_qty
       FROM location l
       LEFT JOIN stock_policy sp ON sp.location_id = l.id AND sp.part_id = ?
      WHERE l.deleted_at IS NULL
      ORDER BY CAST(l.id AS INTEGER)`,
    [pid, pid]
  );

  const ledger = await all(
    `SELECT m.id, l.code AS location_code, m.delta, m.reason, m.created_at
       FROM stock_movement m JOIN location l ON l.id = m.location_id
      WHERE m.part_id = ?
      ORDER BY CAST(m.id AS INTEGER) DESC LIMIT 25`,
    [pid]
  );

  // Rust: COALESCE(price_usd_minor, latest tier='list' in any currency).
  let priceCents = nnum(d["price_usd_minor"]);
  if (priceCents == null) {
    const fallback = await one<Row>(
      `SELECT amount_minor FROM price WHERE part_id = ? AND tier = 'list'
        AND deleted_at IS NULL ORDER BY valid_from DESC LIMIT 1`,
      [pid]
    );
    priceCents = nnum(fallback?.["amount_minor"]);
  }

  const stockLines = stock.map((s) => ({
    location_id: numId(s["id"], "location.id"),
    location_code: str(s["code"]),
    location_name: str(s["name"]),
    on_hand: Number(s["on_hand"]),
    bin: nstr(s["bin"]),
    reorder_point: nnum(s["reorder_point"]),
    reorder_qty: nnum(s["reorder_qty"]),
  }));

  return {
    id: numId(d["id"], "part.id"),
    sku: str(d["sku"]),
    locator: nstr(d["locator"]),
    catalogue_pn: nstr(d["catalogue_pn"]),
    inventory_pn: nstr(d["inventory_pn"]),
    mpn: nstr(d["mpn"]),
    name: str(d["name"]),
    side: nstr(d["side"]),
    make: nstr(d["make"]),
    model: nstr(d["model"]),
    drawing_no: nstr(d["drawing_no"]),
    diagram_item_no: nnum(d["diagram_item_no"]),
    category_code: nstr(d["category_code"]),
    category_name: nstr(d["category_name"]),
    match_status: nstr(d["match_status"]),
    notes: nstr(d["notes"]),
    status: nstr(d["status"]),
    brand: nstr(brand?.["brand"]),
    description: nstr(d["description"]),
    price_cents: priceCents,
    list_price_minor: nnum(d["list_price_minor"]),
    total_on_hand: stockLines.reduce((t, s) => t + s.on_hand, 0),
    stock: stockLines,
    ledger: ledger.map((m) => ({
      id: numId(m["id"], "stock_movement.id"),
      location_code: str(m["location_code"]),
      delta: Number(m["delta"]),
      reason: str(m["reason"]),
      created_at: str(m["created_at"]),
    })),
    images: images.map((i) => ({
      id: numId(i["id"], "part_image.id"),
      path: str(i["path"]),
      kind: str(i["kind"]),
      is_primary: bool(i["is_primary"]),
    })),
    diagram_image: nstr(d["diagram_image"]),
    diagram_item: nstr(d["diagram_item"]), // always null until M0.2 — see GAPS
    model_3d: nstr(d["model_3d"]),
  };
}

// ─── flat lists ──────────────────────────────────────────────────────────────

async function listParts(): Promise<unknown[]> {
  noteGaps();
  const rows = await all(`SELECT * FROM (${PART_DETAIL_SQL}) ORDER BY category_code, sku`);
  return rows.map((r) => ({
    id: numId(r["id"], "part.id"),
    sku: str(r["sku"]),
    locator: nstr(r["locator"]),
    name: str(r["name"]),
    side: nstr(r["side"]),
    category_code: nstr(r["category_code"]),
    catalogue_pn: nstr(r["catalogue_pn"]),
    inventory_pn: nstr(r["inventory_pn"]),
    status: nstr(r["status"]),
    match_status: nstr(r["match_status"]),
    qty_on_hand: Number(r["qty_on_hand"]),
    bin: nstr(r["bin"]),
    price_cents: nnum(r["price_usd_minor"]),
    has_photo: r["primary_image"] != null,
    has_diagram: r["diagram_image"] != null,
    has_model: r["model_3d"] != null,
  }));
}

async function jefreyCatalogue(): Promise<unknown[]> {
  noteGaps();
  const rows = await all(`SELECT * FROM (${PART_DETAIL_SQL}) ORDER BY CAST(id AS INTEGER)`);
  return rows.map((r) => ({
    id: numId(r["id"], "part.id"),
    sku: str(r["sku"]),
    name: str(r["name"]),
    side: nstr(r["side"]),
    inv_pn: nstr(r["inventory_pn"]),
    cat_pn: nstr(r["catalogue_pn"]),
    locator: nstr(r["locator"]),
    section: nstr(r["category_name"]),
    loc: nstr(r["bin"]),
    qty: Number(r["qty_on_hand"]),
    cost_minor: nnum(r["price_zar_minor"]),
    list_minor: nnum(r["list_price_minor"]),
    dwg: nstr(r["drawing_no"]),
    has_photo: r["primary_image"] != null,
    notes: nstr(r["notes"]),
    match_status: nstr(r["match_status"]),
  }));
}

async function listCategories(): Promise<unknown[]> {
  const rows = await all(
    `SELECT id, code, name FROM category WHERE deleted_at IS NULL ORDER BY code`
  );
  return rows.map((r) => ({
    id: numId(r["id"], "category.id"),
    code: str(r["code"]),
    name: str(r["name"]),
  }));
}

async function listLocations(): Promise<unknown[]> {
  const rows = await all(
    `SELECT id, code, name FROM location WHERE deleted_at IS NULL ORDER BY CAST(id AS INTEGER)`
  );
  return rows.map((r) => ({
    id: numId(r["id"], "location.id"),
    code: str(r["code"]),
    name: str(r["name"]),
  }));
}

async function getCompany(): Promise<unknown> {
  // Rust reads `WHERE id=1`; there is only ever one company row.
  const c =
    (await one(`SELECT name, address, phone, email, tax_id, currency, terms
                 FROM company WHERE id = '1'`)) ??
    (await one(`SELECT name, address, phone, email, tax_id, currency, terms
                 FROM company LIMIT 1`));
  if (!c) throw new Error("[CTP web] no company row has synced yet.");
  return {
    name: str(c["name"]),
    address: nstr(c["address"]),
    phone: nstr(c["phone"]),
    email: nstr(c["email"]),
    tax_id: nstr(c["tax_id"]),
    currency: str(c["currency"]),
    terms: nstr(c["terms"]),
  };
}

// ─── registry ────────────────────────────────────────────────────────────────

const PORTED: Record<string, Handler> = {
  search_parts: (a) => searchParts(String(a["query"] ?? "")),
  part_detail: (a) => partDetail(Number(a["partId"])),
  list_parts: () => listParts(),
  list_categories: () => listCategories(),
  list_locations: () => listLocations(),
  jefrey_catalogue: () => jefreyCatalogue(),
  get_company: () => getCompany(),
};

export const webBackend: Backend = {
  async call<T>(cmd: string, args?: Record<string, unknown>): Promise<T> {
    const handler = PORTED[cmd];
    if (!handler) {
      throw new Error(
        `[CTP web] "${cmd}" is not available in the browser build yet. ` +
          `It still lives in the Rust layer — port it in src/data/backend.web.ts.`
      );
    }
    return (await handler(args ?? {})) as T;
  },
};

/** True when a command works in the browser build. Use to hide desktop-only UI on mobile. */
export function isPortedToWeb(cmd: string): boolean {
  return cmd in PORTED;
}
